# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  google_client_secret: <%= ENV['GOOLGE_SECRET'] %>
  jwt_secret: 3d515cada96de4bd748fc4b0ab7862c05
  jwt_algorithm: HS512
  secret_key_base: 9fbeff260ec76da4dcc8b9106bc2252eb0b8160f63eeb4fbb42dadab0bc49e880b3a61ded08d49382a69c70f0d08dc7cd4d92e7fc54d964d6ddd915ecf0eb3e6

test:
  secret_key_base: 402ef4e0ba0ba1f7ac379cb6ac9d1f156f0ddfdda17ff228a0c65502cce9b0041f8911182d2a16f9ebe4995839a64df4dec12d388198a30c35d4eb0fb77d619f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_oauth_secret: <%= ENV['GOOLGE_SECRET'] %>
  jwt_secret: 04b55bbdf65b3f54b403c7d7a3fd2074a
  jwt_algorithm: HS512
  secret_key_base: e9ed6534e34df021aa88ce008409445b6ecca0da3c8b638e75e049f3b76f343f083972ac69fa447eb1bc35c44ed4e8c4785601a7782d4a9a36d5a73819bc86d8
